# frozen_string_literal: true

# Force CocoaPods to use git specs repo (avoids CDN timeouts)
source 'https://github.com/CocoaPods/Specs.git'

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods', :deterministic_uuids => false

prepare_react_native_project!

target 'familysync' do
  use_expo_modules!

  config = use_native_modules! rescue nil
  react_native_path = (config && config[:reactNativePath]) ? config[:reactNativePath] : "../node_modules/react-native"

  use_react_native!(
    :path => react_native_path,
    :hermes_enabled => (podfile_properties['expo.jsEngine'] || 'hermes') == 'hermes',
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      react_native_path,
      :mac_catalyst_enabled => false
    )

    def disable_user_script_sandboxing!(project)
      return if project.nil?
      project.targets.each do |t|
        t.build_configurations.each do |c|
          c.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
        end
      end
      project.save
    end

    disable_user_script_sandboxing!(installer.pods_project)

    if installer.respond_to?(:aggregate_targets) && installer.aggregate_targets&.first
      user_project = installer.aggregate_targets.first.user_project rescue nil
      disable_user_script_sandboxing!(user_project)
    end
  end
end

